In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [3]:
#BASIC COMPUTATIONS OF R


# BASIC COMPUTATIONS OF R

In [4]:
5 + 3

[1] 8

In [5]:
6/3

[1] 2

In [6]:
(3 * 8)/(2 * 3)

[1] 4

In [7]:
log(12)

[1] 2.484907

In [8]:
sqrt(121)

[1] 11

# Central Tendency and Variability

##### 1.mean(x) Mean of the numbers in vector x.
##### 2.median(x) Median of the numbers in vector x.
##### 3.var(x) Estimated variances of population from which the numbers in vector x are sampled.
##### 4.sd(x) Estimated standard deviation of population from which the numbers in vector x are sampled.

In [13]:
x <- 1:10
cat(x)
cat('Mean of x is' ,mean(x))
cat( 'median of x is' ,median(x))
cat( 'Variance is' ,var(x))
cat( 'Standard deviation is' ,sd(x))


1 2 3 4 5 6 7 8 9 10Mean of x is 5.5median of x is 5.5Variance is 9.166667Standard deviation is 3.02765

###### this problem can be solved by using new line function"\n" also.

In [14]:
cat(x,'\n')
cat('Mean of x is' ,mean(x),'\n')
cat( 'median of x is' ,median(x),'\n')
cat( 'Variance is' ,var(x),'\n')
cat( 'Standard deviation is' ,sd(x)'\n')


1 2 3 4 5 6 7 8 9 10 
Mean of x is 5.5 
median of x is 5.5 
Variance is 9.166667 
Standard deviation is 3.02765 


In [16]:
x <- 8 + 7
x

[1] 15

# *Essentials of R programming*

In [17]:
# creation of character variable
x <- 'dataset'
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] "dataset"

[1] "character"

[1] "character"

[1] 1

NULL

In [18]:
# creation of numeric variables
x <- 23
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 23

[1] "numeric"

[1] "double"

[1] 1

NULL

In [19]:
# creating of integer variables
x <- 23L
x
class(x)
typeof(x)
length(x)
attributes(x)


[1] 23

[1] "integer"

[1] "integer"

[1] 1

NULL

In [20]:
# creating of complex variables
x <- 2 + 3i
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] 2+3i

[1] "complex"

[1] "complex"

[1] 1

NULL

In [21]:
# creating of logical variables
x <- TRUE
x
class(x)
typeof(x)
length(x)
attributes(x)

[1] TRUE

[1] "logical"

[1] "logical"

[1] 1

NULL

# ******DATA STRUCTURES******

### VECTOR

In [22]:
vector()

logical(0)

In [23]:
vector('character',length = 5)

[1] "" "" "" "" ""

In [24]:
character(5)

[1] "" "" "" "" ""

In [25]:
numeric(5)

[1] 0 0 0 0 0

In [26]:
logical(5)

[1] FALSE FALSE FALSE FALSE FALSE

In [28]:
# numeric vector having 5  elements
x <- c(12,23,34,45,56)

In [29]:
x
class(x)

[1] 12 23 34 45 56

[1] "numeric"

In [30]:
# integer vector having 5  elements
x <- c(12L,23L,34L,45L,56L)

In [31]:
x
class(x)
length(x)

[1] 12 23 34 45 56

[1] "integer"

[1] 5

In [32]:
# logical vector having 5  elements
y <- c(TRUE,TRUE,FALSE,FALSE,TRUE)
y
class(y)
length(y)


[1]  TRUE  TRUE FALSE FALSE  TRUE

[1] "logical"

[1] 5

In [33]:
# character vector having 3 elements
z <- c('Bhargav','Ramireddy','Vishnu')
z
class(z)
length(z)

[1] "Bhargav"   "Ramireddy" "Vishnu"

[1] "character"

[1] 3

# Adding elements

In [34]:
# add elements at the end
print('Elements in z before')
z
z <- c(z,'Bannureddy')
print('Elements in z after adding the last element')
z

[1] "Elements in z before"


[1] "Bhargav"   "Ramireddy" "Vishnu"

[1] "Elements in z after adding the last element"


[1] "Bhargav"    "Ramireddy"  "Vishnu"     "Bannureddy"

In [35]:
# add elements at the front
print('Elements in z before')
z
z <- c('Ramireddy is Bannureddy',z)
print('Elements in z after adding the front element')
z

[1] "Elements in z before"


[1] "Bhargav"    "Ramireddy"  "Vishnu"     "Bannureddy"

[1] "Elements in z after adding the front element"


[1] "Ramireddy is Bannureddy" "Bhargav"                
[3] "Ramireddy"               "Vishnu"                 
[5] "Bannureddy"

### Vectors from a Sequence of Numbers

In [36]:
a <- 1:10
a

[1]  1  2  3  4  5  6  7  8  9 10

In [37]:
seq(10)

[1]  1  2  3  4  5  6  7  8  9 10

In [39]:
seq(from = 1,to = 10,by = 0.1)

[1]  1.0  1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.0  2.1  2.2  2.3  2.4
[16]  2.5  2.6  2.7  2.8  2.9  3.0  3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9
[31]  4.0  4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.0  5.1  5.2  5.3  5.4
[46]  5.5  5.6  5.7  5.8  5.9  6.0  6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
[61]  7.0  7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.0  8.1  8.2  8.3  8.4
[76]  8.5  8.6  8.7  8.8  8.9  9.0  9.1  9.2  9.3  9.4  9.5  9.6  9.7  9.8  9.9
[91] 10.0

## Other special values

In [40]:
1/0

[1] Inf

In [41]:
0/0

[1] NaN

In [43]:
exp(Inf)

[1] Inf

In [44]:
exp(-Inf)

[1] 0

In [45]:
Inf-Inf

[1] NaN

In [46]:
log(0)

[1] -Inf

# What happens when u mix types inside a vector?

In [47]:
a <- c(1.7,'a')
a

[1] "1.7" "a"

In [48]:
b <- c(TRUE, 2,3, FALSE)
b

[1] 1 2 3 0

In [49]:
c <- c('a',TRUE)
c

[1] "a"    "TRUE"

# Explicit Type of conversions

In [50]:
as.numeric("1")

[1] 1

In [53]:
as.numeric(c("45","66"))

[1] 45 66

In [54]:
as.numeric(c("45","66",'six'))

Warning message in eval(expr, envir, enclos):
“NAs introduced by coercion”

[1] 45 66 NA

In [55]:
as.character(22)

[1] "22"

In [56]:
as.character(c(22,34,56))

[1] "22" "34" "56"

# Matrix

In [58]:
m <- matrix(nrow = 2, ncol = 2)
m

[,1] [,2]
[1,] NA   NA  
[2,] NA   NA

In [59]:
dim(m)

[1] 2 2

In [60]:
class(m)

[1] "matrix"

In [61]:
typeof(m)

[1] "logical"

In [62]:
m <- matrix(c(1:3))
print('Given Matrix is')
print(m)
print('Dimensions (size) of given Matrix is')
print(dim(m))
print('Class of given matrix is')
print(class(m))
print('Type of given matrix is')
print(typeof(m))

[1] "Given Matrix is"
     [,1]
[1,]    1
[2,]    2
[3,]    3
[1] "Dimensions (size) of given Matrix is"
[1] 3 1
[1] "Class of given matrix is"
[1] "matrix"
[1] "Type of given matrix is"
[1] "integer"


In [63]:
a <- matrix(1:6, nrow = 2, ncol = 3)
print(a)

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6


In [66]:
m                      <- 1:10
print(m)
print(dim(m))
dim(m) <- c(2,5)
print(m)
print(dim(m))

 [1]  1  2  3  4  5  6  7  8  9 10
NULL
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10
[1] 2 5


# R Program to Take Input From User

## Example:Take input from User

In [67]:
my_name <- readline(prompt="Enter name: ")
my_age <- readline(prompt="Enter the age: ")
my_age <- as.integer(my_age)
print(paste("Hi, ", my_name, "next year you will be ",my_age+1, "years old."))

Enter name: Vishnusasank
Enter the age: 18
[1] "Hi,  Vishnusasank next year you will be  19 years old."


In [68]:
w <- readline()
w

HI this is vishnusasank kambham


[1] "HI this is vishnusasank kambham"